// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string     `json:"id"`
	Text      string     `json:"text"`
	PostID    string     `json:"postId"`
	ParentID  *string    `json:"parentId,omitempty"`
	CreatedAt string     `json:"createdAt"`
	Children  []*Comment `json:"children"`
}

type Mutation struct {
}

type Post struct {
	ID            string     `json:"id"`
	Text          string     `json:"text"`
	AllowComments bool       `json:"allowComments"`
	Comments      []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
